utils: add ip address related functions
longhorn/go-common-libs pull request #7
Opened 2023-12-29 12:54 UTC by derekbit

Longhorn/longhorn#6138

2023-12-29 17:40 UTC, innobead requested changes

2023-12-29 17:40 UTC, innobead commented on utils/ip.go
> +// GetIPForPod returns the IP address for the pod.
Suggest `// GetIPForPod returns the IP address for the pod from the storage network first or the cluster network.`

2023-12-29 17:40 UTC, innobead commented on utils/ip.go
> +func GetExternalIP() (string, error) {
It seems getting any external IP. Suggest `GetAnyExternalIP`.

2023-12-29 17:40 UTC, innobead commented on utils/ip_test.go
> +func (s *TestSuite) GetLocalIPv4fromInterface(c *C) {
The test function name is incorrect. Should be `TestIsLoopbackHost`

2023-12-30 06:50 UTC, derekbit commented
All are addressed. Thank you.

2023-12-30 06:58 UTC, innobead requested changes

2023-12-30 06:58 UTC, innobead commented on utils/ip_test.go
> +func (s *TestSuite) GetIsLoopbackHost(c *C) {
This should be "TestIsLoopbackHost"?

2023-12-30 08:04 UTC, innobead approved these changes

2023-12-30 08:05 UTC, merged

2023-12-30 08:05 UTC, innobead commented
@derekbit moved ip related code to the `net` package.

2023-12-30 08:10 UTC, derekbit commented on utils/ip_test.go
> +func (s *TestSuite) GetIsLoopbackHost(c *C) {
Ah, forgot prefix..